name: VERDANA-aws

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  #JOB 1 : Backened ecosystem
  BackeEnd-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: backend/package.lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run
        env:
          JWT_Secret: ${{secrets.JWT_Secret}}
          DB_URI: ${{secrets.DB_URI}}

  # Frontend eco system
  FrontEnd-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package.json

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend Application
        run: |
          cd frontend
          npm run build
        env:
          VITE_API_URL: "http://localhost:5000"

